Repository AY2425S1-CS2103T-T10-1/tp, pull requests merged in 2024-10, with the labels that each got.

#57 Update delete command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Enhancement

#56 Update UI
  copyright.txt
  docs/images/Ui.png
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/health-report.png
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Task

#62 Fix Ui
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
Labels: type.Bug

#65 Fixes bug where tags and appointments were overridden accidentally
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: severity.Medium

#78 Add command summary to help window
  docs/UserGuide.md
  docs/images/helpwindow.png
  src/main/java/seedu/address/ui/CommandSummary.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/ui/CommandSummaryTest.java
Labels: type.Story, type.Enhancement

#74 Implement notes for patients
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/StarCommand.java
  src/main/java/seedu/address/logic/commands/UnstarCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/StarCommandTest.java
  src/test/java/seedu/address/logic/commands/UnstarCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/NoteDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.Medium

#88 Sort Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
Labels: type.Story, priority.High

#86 Add confirmation for deleting and clearing all contacts
  docs/UserGuide.md
  docs/images/clearConfirmation.png
  docs/images/deleteConfirmation.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/ConfirmationWindow.java
  src/main/java/seedu/address/ui/UiPart.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/ui/ConfirmationWindowTest.java
Labels: type.Story, type.Enhancement, priority.Medium

#93 Update content and diagrams in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task, priority.High

#97 Update help window screenshot in User Guide
  docs/UserGuide.md
  docs/images/helpWindow.png
  docs/images/helpwindow.png
Labels: type.Task

#98 Update Storage's .puml file to reflect new fields
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Enhancement, type.Task, priority.Low

#102 Improve code quality
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/controller/ConfirmationBypassController.java
  src/main/java/seedu/address/logic/commands/controller/ConfirmationController.java
  src/main/java/seedu/address/logic/commands/controller/ConfirmationWindowController.java
  src/main/java/seedu/address/ui/ConfirmationWindow.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/UiPart.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/ui/ConfirmationWindowTest.java
Labels: type.Task, priority.Medium

#105 Improve Help Window UI
  docs/images/helpWindow.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#108 Update JAR file name to reflect as MediContact
  build.gradle
Labels: alpha-bug

#117 Fix confirmation alert not triggered for clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: priority.High, alpha-bug
