Repository AY2425S1-CS2103T-T10-1/tp, pull requests merged in 2024-11, with the labels that each got.

#129 Fix bug where long inputs are not displayed entirely
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.Medium

#152 Fix unusual behaviour of confirmation window when in fullscreen
  src/main/java/seedu/address/ui/ConfirmationWindow.java
Labels: type.Enhancement, type.Task, priority.Medium

#157 Fix alpha bugs found regarding Notes and Appointments
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/note/Note.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#160 Update Sort Command: Fix Issue #123
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: priority.High, alpha-bug

#161 Update Delete Command: Error Handling Fix Issues #131 and #143
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High, alpha-bug

#175 Improve UI and move folder
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/ui/controller/ConfirmationBypassController.java
  src/main/java/seedu/address/ui/controller/ConfirmationController.java
  src/main/java/seedu/address/ui/controller/ConfirmationWindowController.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Enhancement, priority.Medium

#176 Update UG color palette
  docs/stylesheets/main.css
Labels: type.Task, priority.High

#178 Update Developer Guide, fix User Guide bug and rename a method
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: type.Task, priority.High

#180 Update colours of Confirmation Window and update screenshot in UG
  docs/images/Ui.png
  docs/images/clearConfirmation.png
  docs/images/deleteConfirmation.png
  src/main/java/seedu/address/ui/ConfirmationWindow.java
Labels: type.Task, priority.Medium

#182 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/addEvie.png
  docs/images/deleteExpected.png
  docs/images/editJohn.png
  docs/images/filterResult.png
  docs/images/findResult.png
  docs/images/listResult.png
  docs/images/listStarResult.png
  docs/images/noteResult.png
  docs/images/sortResult.png
  docs/images/starResult.png
  docs/images/unstarResult.png
  docs/images/viewResult.png
Labels: type.Task, type.Bug, priority.High

#188 Fix UG bug
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#268 Increase font size
  docs/stylesheets/main.css
Labels: type.Task, priority.Medium

#266 Fix bugs found in PE-D
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/ConfirmationWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task, priority.High

#279 Updated User Guide Styling
  docs/UserGuide.md
Labels: priority.High

#277 Add tests and fix bugs
  docs/AboutUs.md
  docs/_markbind/layouts/default.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StarCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnstarCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/ui/CommandSummaryTest.java
Labels: type.Task, priority.Medium

#284 Update Ui
  docs/UserGuide.md
  docs/images/Ui.png
Labels: type.Task, priority.High

#286 Update DG: Make Use cases more target audience specific
  docs/DeveloperGuide.md
Labels: priority.High

#289 Update images in UG
  docs/UserGuide.md
  docs/images/clearConfirmation.png
  docs/images/deleteConfirmation.png
  docs/images/helpWindow.png
Labels: type.Task, priority.Medium

#291 Add to FAQ and glossaries
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#297 Update help window, ug and dg
  docs/DeveloperGuide.md
  docs/images/helpWindow.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.Medium
